/*

 Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

*/

class Solution 
{

    public:
    
    char findTheDifference(string s, string t) 
    {
        int index, sizeS = s.size(), sizeT = t.size();
        map<char, int> charMapOne, charMapTwo;
        map<char, int>::iterator mapIteratorOne, mapIteratorTwo;
            
        for(index = 0; index < sizeS; index++)    
        {
            charMapOne[s[index]]++;
        }
        
        for(index = 0; index < sizeT; index++)    
        {
            charMapTwo[t[index]]++;
        }
        
        for(index = 0; index < sizeT; index++)    
        {
            mapIteratorOne = charMapOne.find(t[index]);
            mapIteratorTwo = charMapTwo.find(t[index]);
            
            if(mapIteratorOne->second != mapIteratorTwo->second)
            {
                return mapIteratorTwo->first;
            }
        }
        
        return '\0';
    }
};
